# Training Configuration for Khmer OCR Seq2Seq Model

# Model Architecture
model:
  # Encoder Configuration (CRNN)
  encoder:
    input_channels: 1
    conv_channels: [64, 128, 256, 256, 512, 512, 512]
    kernel_sizes: [3, 3, 3, 3, 3, 3, 3]
    pool_sizes: [[2,2], [2,2], [2,1], [2,1]]
    gru_hidden_size: 256
    gru_num_layers: 2
    bidirectional: true
  
  # Attention Configuration
  attention:
    type: "bahdanau"
    hidden_size: 512
    
  # Decoder Configuration
  decoder:
    embedding_dim: 256
    hidden_size: 512
    vocab_size: 117
    max_length: 256

# Training Parameters
training:
  epochs: 150
  batch_size: 64
  learning_rate: 1e-6
  optimizer: "adam"
  loss_function: "cross_entropy"
  teacher_forcing_ratio: 1.0
  gradient_clip: 5.0
  gradient_accumulation_steps: 1
  
# Data Parameters
data:
  image_height: 32
  vocab_size: 117
  augmentation:
    probability: 0.5
    gaussian_blur:
      sigma_range: [0, 1.5]
    morphological:
      kernel_sizes: [2, 3]
      operations: ["dilation", "erosion"]
    noise:
      blob_radius: [1, 3]
      background_intensity: 0.1
    concatenation:
      probability: 0.5

# Paths Configuration
paths:
  data_dir: "data/"
  model_dir: "models/"
  checkpoint_dir: "models/checkpoints/"
  log_dir: "logs/"
  font_dir: "data/fonts/"

# Validation and Evaluation
validation:
  val_split: 0.1
  eval_frequency: 1000  # steps
  save_frequency: 5000  # steps
  
# Hardware Configuration
hardware:
  device: "cuda"  # cuda, cpu, mps
  num_workers: 4
  pin_memory: true 