# Khmer Vocabulary Configuration
# Total: 117 tokens (4 special + 113 Khmer characters)
 
special_tokens:
  sos: "SOS"
  eos: "EOS"
  pad: "PAD"
  unk: "UNK"

# Token indices
special_indices:
  sos_idx: 0
  eos_idx: 1
  pad_idx: 2
  unk_idx: 3

# Vocabulary categories
vocabulary:
  # Special tokens (4)
  special_count: 4
  
  # Khmer numbers (10)
  khmer_numbers: ["០", "១", "២", "៣", "៤", "៥", "៦", "៧", "៨", "៩"]
  
  # Arabic numbers (10)
  arabic_numbers: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
  
  # Consonants (33)
  consonants: [
    "ក", "ខ", "គ", "ឃ", "ង", "ច", "ឆ", "ជ", "ឈ", "ញ",
    "ដ", "ឋ", "ឌ", "ឍ", "ណ", "ត", "ថ", "ទ", "ធ", "ន",
    "ប", "ផ", "ព", "ភ", "ម", "យ", "រ", "ល", "វ", "ស",
    "ហ", "ឡ", "អ"
  ]
  
  # Independent vowels (12)
  independent_vowels: [
    "ឥ", "ឦ", "ឧ", "ឩ", "ឪ", "ឫ", "ឬ", "ឭ", "ឮ", "ឯ", "ឰ", "ឱ"
  ]
  
  # Dependent vowels (23)
  dependent_vowels: [
    "ា", "ិ", "ី", "ឹ", "ឺ", "ុ", "ូ", "ួ", "ើ", "ឿ",
    "ៀ", "េ", "ែ", "ៃ", "ោ", "ៅ", "ាំ", "ះ", "ៈ", "ំ",
    "ុំ", "ាៈ", "េៈ"
  ]
  
  # Subscript (1)
  subscript: ["្"]
  
  # Diacritics (10)
  diacritics: ["់", "៉", "៊", "័", "៏", "៌", "៍", "៎", "៑", "៓"]
  
  # Symbols (14)
  symbols: ["(", ")", ",", ".", "៕", "។", "ៗ", "?", " ", ";", ":", "-", "!", "\""]

# Total vocabulary size
total_size: 117 