# Complete Khmer OCR Vocabulary - 132 tokens
# Includes all Khmer characters for comprehensive text recognition

vocab_size: 132

# Complete vocabulary list in order
vocabulary:
  # Special tokens (4)
  - "SOS"
  - "EOS"
  - "PAD"
  - "UNK"
  
  # Khmer numbers (10)
  - "០"
  - "១"
  - "២"
  - "៣"
  - "៤"
  - "៥"
  - "៦"
  - "៧"
  - "៨"
  - "៩"
  
  # Arabic numbers (10)
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  
  # Consonants (35)
  - "ក"
  - "ខ"
  - "គ"
  - "ឃ"
  - "ង"
  - "ច"
  - "ឆ"
  - "ជ"
  - "ឈ"
  - "ញ"
  - "ដ"
  - "ឋ"
  - "ឌ"
  - "ឍ"
  - "ណ"
  - "ត"
  - "ថ"
  - "ទ"
  - "ធ"
  - "ន"
  - "ប"
  - "ផ"
  - "ព"
  - "ភ"
  - "ម"
  - "យ"
  - "រ"
  - "ល"
  - "វ"
  - "ឝ"
  - "ឞ"
  - "ស"
  - "ហ"
  - "ឡ"
  - "អ"
  
  # Independent vowels (16)
  - "ឣ"
  - "ឤ"
  - "ឥ"
  - "ឦ"
  - "ឧ"
  - "ឨ"
  - "ឩ"
  - "ឪ"
  - "ឫ"
  - "ឬ"
  - "ឭ"
  - "ឮ"
  - "ឯ"
  - "ឰ"
  - "ឱ"
  - "ឲ"
  
  # Dependent vowels (23)
  - "ា"
  - "ិ"
  - "ី"
  - "ឹ"
  - "ឺ"
  - "ុ"
  - "ូ"
  - "ួ"
  - "ើ"
  - "ឿ"
  - "ៀ"
  - "េ"
  - "ែ"
  - "ៃ"
  - "ោ"
  - "ៅ"
  - "ាំ"
  - "ះ"
  - "ៈ"
  - "ំ"
  - "ុំ"
  - "ាៈ"
  - "េៈ"
  
  # Subscript (1)
  - "្"
  
  # Diacritics (10)
  - "់"
  - "៉"
  - "៊"
  - "័"
  - "៏"
  - "៌"
  - "៍"
  - "៎"
  - "៑"
  - "៓"
  
  # Symbols (23)
  - "("
  - ")"
  - ","
  - "."
  - "៕"
  - "។"
  - "៖"
  - "ៗ"
  - "៘"
  - "៙"
  - "៚"
  - "៛"
  - "ៜ"
  - "៝"
  - "?"
  - " "
  - ";"
  - ":"
  - "-"
  - "!"
  - "\""
  - "["
  - "]"

# Special token indices
special_indices:
  SOS: 0
  EOS: 1
  PAD: 2
  UNK: 3 